SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Asistencia](
	[IDAsistencia] [int] NOT NULL,
	[IDMiembro_Sucursal] [smallint] NOT NULL,
	[FechaHora_Entrada] [datetime] NOT NULL,
	[FechaHora_Salida] [datetime] NOT NULL,
	[IDAcceso] [smallint] NOT NULL,
 CONSTRAINT [PK_Asistencia] PRIMARY KEY CLUSTERED 
(
	[IDAsistencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Canje](
	[IDCanje] [smallint] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Fecha_canje] [date] NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
	[IDMiembro_Sucursal] [smallint] NOT NULL,
 CONSTRAINT [PK_Canje] PRIMARY KEY CLUSTERED 
(
	[IDCanje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Ciudad](
	[IDCiudad] [smallint] NOT NULL,
	[Nombre] [nvarchar](350) NOT NULL,
	[IDPais] [smallint] NOT NULL,
 CONSTRAINT [PK_Ciudad] PRIMARY KEY CLUSTERED 
(
	[IDCiudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CondicionMedica](
	[IDCondicion] [smallint] NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CondicionMedica] PRIMARY KEY CLUSTERED 
(
	[IDCondicion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Estado](
	[IDEstado] [smallint] NOT NULL,
	[Nombre] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Estado] PRIMARY KEY CLUSTERED 
(
	[IDEstado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Genero](
	[IDGenero] [smallint] NOT NULL,
	[Nombre] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_Genero] PRIMARY KEY CLUSTERED 
(
	[IDGenero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Grupo](
	[IDGrupo] [smallint] NOT NULL,
	[Nombre] [nvarchar](150) NOT NULL,
	[Fecha_creacion] [date] NOT NULL,
 CONSTRAINT [PK_Grupo] PRIMARY KEY CLUSTERED 
(
	[IDGrupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Membresia](
	[IDMembresia] [smallint] NOT NULL,
	[Fecha_Inicio] [date] NOT NULL,
	[Fecha_fin] [date] NOT NULL,
	[IDMiembro] [smallint] NOT NULL,
	[IDTipo_Membresia] [smallint] NOT NULL,
 CONSTRAINT [PK_Membresia] PRIMARY KEY CLUSTERED 
(
	[IDMembresia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Miembro](
	[IDMiembro] [smallint] NOT NULL,
	[Nombre1] [nvarchar](150) NOT NULL,
	[Nombre2] [nvarchar](150) NULL,
	[Apellido1] [nvarchar](150) NOT NULL,
	[Apellido2] [nvarchar](150) NULL,
	[Identificacion] [nvarchar](13) NOT NULL,
	[Fecha_registro] [date] NOT NULL,
	[Fecha_nacimiento] [date] NOT NULL,
	[IDGenero] [smallint] NOT NULL,
	[Altura] [decimal](5, 2) NOT NULL,
	[Peso_inical] [decimal](5, 2) NOT NULL,
	[IDCondicion] [smallint] NULL,
	[estaSuspendido] [bit] NOT NULL,
 CONSTRAINT [PK_Ususario] PRIMARY KEY CLUSTERED 
(
	[IDMiembro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Miembro_Grupo](
	[IDGrupo] [smallint] NOT NULL,
	[IDMiembro] [smallint] NOT NULL,
	[Fecha_entrada] [date] NOT NULL,
	[Fecha_salida] [date] NULL,
	[esLider] [bit] NOT NULL,
 CONSTRAINT [PK_Miembro_Grupo] PRIMARY KEY CLUSTERED 
(
	[IDGrupo] ASC,
	[IDMiembro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Miembro_reto](
	[IDMiembro] [smallint] NOT NULL,
	[IDReto] [smallint] NOT NULL,
	[Progreso] [decimal](4, 2) NOT NULL,
	[Fecha_inscripcion] [datetime] NOT NULL,
	[Fecha_completado] [datetime] NULL,
	[IDEstado] [smallint] NOT NULL,
 CONSTRAINT [PK_Miembro_reto] PRIMARY KEY CLUSTERED 
(
	[IDMiembro] ASC,
	[IDReto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Miembro_Sucursal](
	[IDMiembro_Sucursal] [smallint] NOT NULL,
	[Fecha_inicio] [date] NOT NULL,
	[Fecha_cancelacion] [date] NULL,
	[esPrincipal] [bit] NOT NULL,
	[IDSucursal] [smallint] NOT NULL,
	[IDMiembro] [smallint] NOT NULL,
 CONSTRAINT [PK_Memebresia] PRIMARY KEY CLUSTERED 
(
	[IDMiembro_Sucursal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MiembroAcceso](
	[IDAcceso] [smallint] NOT NULL,
	[InformacionEncriptada] [nvarchar](max) NOT NULL,
	[IDTipoAcceso] [smallint] NOT NULL,
	[IDMiembro] [smallint] NOT NULL,
 CONSTRAINT [PK_MiembroAcceso] PRIMARY KEY CLUSTERED 
(
	[IDAcceso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Origen](
	[IDOrigen] [smallint] NOT NULL,
	[Descripcion] [nvarchar](150) NOT NULL,
	[IDReto] [smallint] NULL,
 CONSTRAINT [PK_Origen] PRIMARY KEY CLUSTERED 
(
	[IDOrigen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Pago](
	[IDPago] [smallint] NOT NULL,
	[Fecha_trasaccion] [date] NOT NULL,
	[Monto_abonado] [decimal](9, 2) NOT NULL,
	[IDMembresia] [smallint] NOT NULL,
 CONSTRAINT [PK_Pago] PRIMARY KEY CLUSTERED 
(
	[IDPago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Pais](
	[IDPais] [smallint] NOT NULL,
	[Nombre] [nvarchar](350) NOT NULL,
 CONSTRAINT [PK_Pais] PRIMARY KEY CLUSTERED 
(
	[IDPais] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Pesaje](
	[IDPesaje] [smallint] NOT NULL,
	[Cantidad] [decimal](5, 2) NOT NULL,
	[Fecha] [date] NOT NULL,
	[IDMiembro] [smallint] NOT NULL,
 CONSTRAINT [PK_Pesaje] PRIMARY KEY CLUSTERED 
(
	[IDPesaje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Punteo](
	[IDPunteo] [smallint] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Fecha_obtenido] [date] NOT NULL,
	[Fecha_vencido] [date] NULL,
	[IDOrigen] [smallint] NOT NULL,
	[IDMiembro] [smallint] NOT NULL,
	[estaActivo] [bit] NOT NULL,
 CONSTRAINT [PK_Punteo] PRIMARY KEY CLUSTERED 
(
	[IDPunteo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Reto](
	[IDReto] [smallint] NOT NULL,
	[Nombre] [nvarchar](150) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
	[Fecha_inicio] [datetime] NOT NULL,
	[Fecha_fin] [date] NOT NULL,
	[Puntos_aganar] [int] NOT NULL,
	[Meta_cantidad] [decimal](6, 2) NOT NULL,
	[IDUnidadMedicion] [smallint] NOT NULL,
	[IDSucursal] [smallint] NULL,
	[esGrupal] [bit] NOT NULL,
 CONSTRAINT [PK_Reto] PRIMARY KEY CLUSTERED 
(
	[IDReto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Reto_Grupal](
	[IDGrupo] [smallint] NOT NULL,
	[IDReto] [smallint] NOT NULL,
	[Fecha_creacion] [date] NOT NULL,
	[Fecha_completado] [date] NULL,
	[IDEstado] [smallint] NOT NULL,
 CONSTRAINT [PK_RetoGrupal] PRIMARY KEY CLUSTERED 
(
	[IDGrupo] ASC,
	[IDReto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Sesion_virtual](
	[IDSesion] [smallint] NOT NULL,
	[FechaHora_inicio] [datetime] NOT NULL,
	[Duracion] [decimal](5, 2) NOT NULL,
	[IDMembresia] [smallint] NOT NULL,
 CONSTRAINT [PK_Sesion_virtual] PRIMARY KEY CLUSTERED 
(
	[IDSesion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Sucursal](
	[IDSucursal] [smallint] NOT NULL,
	[Nombre] [nvarchar](150) NOT NULL,
	[Capacidad] [smallint] NOT NULL,
	[Direccion] [nvarchar](max) NOT NULL,
	[IDCiudad] [smallint] NOT NULL,
 CONSTRAINT [PK_Sucursal] PRIMARY KEY CLUSTERED 
(
	[IDSucursal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Tipo_Membresia](
	[IDTipo_Membresia] [smallint] NOT NULL,
	[Nombre] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_TipoMembresia] PRIMARY KEY CLUSTERED 
(
	[IDTipo_Membresia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TipoAcceso](
	[IDTipoAcceso] [smallint] NOT NULL,
	[Nombre] [varbinary](50) NOT NULL,
 CONSTRAINT [PK_TipoAcceso] PRIMARY KEY CLUSTERED 
(
	[IDTipoAcceso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Unidad_medicion](
	[IDUnidadMedicion] [smallint] NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Simbolo] [nvarchar](5) NOT NULL,
 CONSTRAINT [PK_Unidad_medicion] PRIMARY KEY CLUSTERED 
(
	[IDUnidadMedicion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Asistencia]  WITH CHECK ADD  CONSTRAINT [FK_Asistencia_Miembro_Sucursal] FOREIGN KEY([IDMiembro_Sucursal])
REFERENCES [Miembro_Sucursal] ([IDMiembro_Sucursal])
GO
ALTER TABLE [Asistencia] CHECK CONSTRAINT [FK_Asistencia_Miembro_Sucursal]
GO
ALTER TABLE [Asistencia]  WITH CHECK ADD  CONSTRAINT [FK_Asistencia_MiembroAcceso] FOREIGN KEY([IDAcceso])
REFERENCES [MiembroAcceso] ([IDAcceso])
GO
ALTER TABLE [Asistencia] CHECK CONSTRAINT [FK_Asistencia_MiembroAcceso]
GO
ALTER TABLE [Canje]  WITH CHECK ADD  CONSTRAINT [FK_Canje_Miembro_Sucursal] FOREIGN KEY([IDMiembro_Sucursal])
REFERENCES [Miembro_Sucursal] ([IDMiembro_Sucursal])
GO
ALTER TABLE [Canje] CHECK CONSTRAINT [FK_Canje_Miembro_Sucursal]
GO
ALTER TABLE [Ciudad]  WITH NOCHECK ADD  CONSTRAINT [FK_Ciudad_Pais] FOREIGN KEY([IDPais])
REFERENCES [Pais] ([IDPais])
GO
ALTER TABLE [Ciudad] NOCHECK CONSTRAINT [FK_Ciudad_Pais]
GO
ALTER TABLE [Membresia]  WITH CHECK ADD  CONSTRAINT [FK_Membresia_Miembro] FOREIGN KEY([IDMiembro])
REFERENCES [Miembro] ([IDMiembro])
GO
ALTER TABLE [Membresia] CHECK CONSTRAINT [FK_Membresia_Miembro]
GO
ALTER TABLE [Membresia]  WITH CHECK ADD  CONSTRAINT [FK_Membresia_Tipo_Membresia] FOREIGN KEY([IDTipo_Membresia])
REFERENCES [Tipo_Membresia] ([IDTipo_Membresia])
GO
ALTER TABLE [Membresia] CHECK CONSTRAINT [FK_Membresia_Tipo_Membresia]
GO
ALTER TABLE [Miembro]  WITH CHECK ADD  CONSTRAINT [FK_Miembro_CondicionMedica] FOREIGN KEY([IDCondicion])
REFERENCES [CondicionMedica] ([IDCondicion])
GO
ALTER TABLE [Miembro] CHECK CONSTRAINT [FK_Miembro_CondicionMedica]
GO
ALTER TABLE [Miembro]  WITH NOCHECK ADD  CONSTRAINT [FK_Miembro_Genero] FOREIGN KEY([IDGenero])
REFERENCES [Genero] ([IDGenero])
GO
ALTER TABLE [Miembro] NOCHECK CONSTRAINT [FK_Miembro_Genero]
GO
ALTER TABLE [Miembro_Grupo]  WITH NOCHECK ADD  CONSTRAINT [FK_Miembro_Grupo_Grupo] FOREIGN KEY([IDGrupo])
REFERENCES [Grupo] ([IDGrupo])
GO
ALTER TABLE [Miembro_Grupo] NOCHECK CONSTRAINT [FK_Miembro_Grupo_Grupo]
GO
ALTER TABLE [Miembro_Grupo]  WITH NOCHECK ADD  CONSTRAINT [FK_Miembro_Grupo_Miembro] FOREIGN KEY([IDMiembro])
REFERENCES [Miembro] ([IDMiembro])
GO
ALTER TABLE [Miembro_Grupo] NOCHECK CONSTRAINT [FK_Miembro_Grupo_Miembro]
GO
ALTER TABLE [Miembro_reto]  WITH NOCHECK ADD  CONSTRAINT [FK_Miembro_reto_Estado] FOREIGN KEY([IDEstado])
REFERENCES [Estado] ([IDEstado])
GO
ALTER TABLE [Miembro_reto] NOCHECK CONSTRAINT [FK_Miembro_reto_Estado]
GO
ALTER TABLE [Miembro_reto]  WITH NOCHECK ADD  CONSTRAINT [FK_Miembro_reto_Miembro] FOREIGN KEY([IDMiembro])
REFERENCES [Miembro] ([IDMiembro])
GO
ALTER TABLE [Miembro_reto] NOCHECK CONSTRAINT [FK_Miembro_reto_Miembro]
GO
ALTER TABLE [Miembro_reto]  WITH NOCHECK ADD  CONSTRAINT [FK_Miembro_reto_Reto] FOREIGN KEY([IDReto])
REFERENCES [Reto] ([IDReto])
GO
ALTER TABLE [Miembro_reto] NOCHECK CONSTRAINT [FK_Miembro_reto_Reto]
GO
ALTER TABLE [Miembro_Sucursal]  WITH NOCHECK ADD  CONSTRAINT [FK_Memebresia_Sucursal] FOREIGN KEY([IDSucursal])
REFERENCES [Sucursal] ([IDSucursal])
GO
ALTER TABLE [Miembro_Sucursal] NOCHECK CONSTRAINT [FK_Memebresia_Sucursal]
GO
ALTER TABLE [Miembro_Sucursal]  WITH NOCHECK ADD  CONSTRAINT [FK_Memebresia_Ususario] FOREIGN KEY([IDMiembro])
REFERENCES [Miembro] ([IDMiembro])
GO
ALTER TABLE [Miembro_Sucursal] NOCHECK CONSTRAINT [FK_Memebresia_Ususario]
GO
ALTER TABLE [MiembroAcceso]  WITH CHECK ADD  CONSTRAINT [FK_MiembroAcceso_Miembro] FOREIGN KEY([IDMiembro])
REFERENCES [Miembro] ([IDMiembro])
GO
ALTER TABLE [MiembroAcceso] CHECK CONSTRAINT [FK_MiembroAcceso_Miembro]
GO
ALTER TABLE [MiembroAcceso]  WITH CHECK ADD  CONSTRAINT [FK_MiembroAcceso_TipoAcceso] FOREIGN KEY([IDTipoAcceso])
REFERENCES [TipoAcceso] ([IDTipoAcceso])
GO
ALTER TABLE [MiembroAcceso] CHECK CONSTRAINT [FK_MiembroAcceso_TipoAcceso]
GO
ALTER TABLE [Origen]  WITH NOCHECK ADD  CONSTRAINT [FK_Origen_Reto] FOREIGN KEY([IDReto])
REFERENCES [Reto] ([IDReto])
GO
ALTER TABLE [Origen] NOCHECK CONSTRAINT [FK_Origen_Reto]
GO
ALTER TABLE [Pago]  WITH CHECK ADD  CONSTRAINT [FK_Pago_Membresia] FOREIGN KEY([IDMembresia])
REFERENCES [Membresia] ([IDMembresia])
GO
ALTER TABLE [Pago] CHECK CONSTRAINT [FK_Pago_Membresia]
GO
ALTER TABLE [Pesaje]  WITH CHECK ADD  CONSTRAINT [FK_Pesaje_Miembro] FOREIGN KEY([IDMiembro])
REFERENCES [Miembro] ([IDMiembro])
GO
ALTER TABLE [Pesaje] CHECK CONSTRAINT [FK_Pesaje_Miembro]
GO
ALTER TABLE [Punteo]  WITH NOCHECK ADD  CONSTRAINT [FK_Punteo_Miembro] FOREIGN KEY([IDMiembro])
REFERENCES [Miembro] ([IDMiembro])
GO
ALTER TABLE [Punteo] NOCHECK CONSTRAINT [FK_Punteo_Miembro]
GO
ALTER TABLE [Punteo]  WITH NOCHECK ADD  CONSTRAINT [FK_Punteo_Origen] FOREIGN KEY([IDOrigen])
REFERENCES [Origen] ([IDOrigen])
GO
ALTER TABLE [Punteo] NOCHECK CONSTRAINT [FK_Punteo_Origen]
GO
ALTER TABLE [Reto]  WITH NOCHECK ADD  CONSTRAINT [FK_Reto_Sucursal] FOREIGN KEY([IDSucursal])
REFERENCES [Sucursal] ([IDSucursal])
GO
ALTER TABLE [Reto] NOCHECK CONSTRAINT [FK_Reto_Sucursal]
GO
ALTER TABLE [Reto]  WITH NOCHECK ADD  CONSTRAINT [FK_Reto_Unidad_medicion] FOREIGN KEY([IDUnidadMedicion])
REFERENCES [Unidad_medicion] ([IDUnidadMedicion])
GO
ALTER TABLE [Reto] NOCHECK CONSTRAINT [FK_Reto_Unidad_medicion]
GO
ALTER TABLE [Reto_Grupal]  WITH NOCHECK ADD  CONSTRAINT [FK_RetoGrupal_Estado] FOREIGN KEY([IDEstado])
REFERENCES [Estado] ([IDEstado])
GO
ALTER TABLE [Reto_Grupal] NOCHECK CONSTRAINT [FK_RetoGrupal_Estado]
GO
ALTER TABLE [Reto_Grupal]  WITH NOCHECK ADD  CONSTRAINT [FK_RetoGrupal_Grupo] FOREIGN KEY([IDGrupo])
REFERENCES [Grupo] ([IDGrupo])
GO
ALTER TABLE [Reto_Grupal] NOCHECK CONSTRAINT [FK_RetoGrupal_Grupo]
GO
ALTER TABLE [Reto_Grupal]  WITH NOCHECK ADD  CONSTRAINT [FK_RetoGrupal_Reto] FOREIGN KEY([IDReto])
REFERENCES [Reto] ([IDReto])
GO
ALTER TABLE [Reto_Grupal] NOCHECK CONSTRAINT [FK_RetoGrupal_Reto]
GO
ALTER TABLE [Sesion_virtual]  WITH CHECK ADD  CONSTRAINT [FK_Sesion_virtual_Membresia] FOREIGN KEY([IDMembresia])
REFERENCES [Membresia] ([IDMembresia])
GO
ALTER TABLE [Sesion_virtual] CHECK CONSTRAINT [FK_Sesion_virtual_Membresia]
GO
ALTER TABLE [Sucursal]  WITH NOCHECK ADD  CONSTRAINT [FK_Sucursal_Ciudad] FOREIGN KEY([IDCiudad])
REFERENCES [Ciudad] ([IDCiudad])
GO
ALTER TABLE [Sucursal] NOCHECK CONSTRAINT [FK_Sucursal_Ciudad]
GO
